application:
  kafka:
    topic: "message-topic"

spring:
  kafka:
    consumer:
      group-id: "random-data-group"
      bootstrap-servers: "localhost:9092"
      client-id: "message-consumer"
      max-poll-interval-ms: 60000
      max-poll-records: 5
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.springframework.kafka.support.serializer.JsonSerializer
